### ISSUE TITLE
eigen appears to ignore verification requests

### ISSUE THREAD

**Issue by paxcoder** [Kalissaac/Eigen#15] opened 2023-03-17 13:14 UTC
Hey.
Something is is broken in eigen and the verification.
I pressed verify on element, and it should pop up on eigen, to verify the session, but it didn't

**Comment by Kalissaac** [comment] 2023-03-20 17:20
Hi, unfortunately Eigen doesn't support interactive verification at the moment. For the time being, you can add your encryption recovery key in the account preferences page, which will verify the device and download all stored encryption keys for past messages. I'll try to work on this soon, but it's relatively complex so it will likely take a decent amount of time.

Closing as duplicate of #12

**Closed as not planned by Kalissaac** 2023-03-20 17:20 UTC
